### ISSUE TITLE
[Question] Frequency and Overhead of Cluster Allocation in Simulation

### ISSUE THREAD

**Issue by J-S-Kim** [EMDC-OS/power-aware-triton#4]
Hello,  

I have a question regarding the cluster simulation discussed in the paper. 

How frequently does cluster allocation occur in the simulation? Additionally, how much computational overhead is involved in this process? There are concerns about the scalability of the system as the number of nodes increases. Could you provide more details?  

Thank you!

**Comment by JunyeolYu** [comment]
Thank you for reaching out with your inquiry.

As stated in the paper, the cluster allocation is performed when a new inference service is **added**, the cloud configuration is **altered**, or the expected peak request rate of an inference service is **changed**. All these events are sporadic.

The complexity of solving Eq. 1 can be approximated to O($mC^m\sum_j (X^{max}_j)^2$), where $C$ is a constant. However, because of ILP solvers' optimization techniques, it is difficult to accurately identify parameters' impact to the computation time. A single-threaded solver took only 35 seconds for cluster allocation when there are 12,000 GPUs of 10 different types serving 100 ML models. If a cloud expands to the point where solving Eq. 1 becomes infeasible, we can partition the cloud into sub-groups.
